// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AvailableData = { symbol: string, interval: string, min_time: bigint, max_time: bigint, };
