// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Trade } from "./Trade";

export type BacktestResult = { total_trades: number, win_rate: string, total_pnl: string, trades: Array<Trade>, };
