// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BollingerSettings = { length: number, std_dev: string, buy_amount: string, daily_drawdown_limit: string, };
