// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatMessage = { id: number, user_id: number | null, sender: string, text: string, created_at: string, recipient_id: number | null, is_read: boolean | null, session_id: string | null, };
