// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DcaProSettings = { base_order_size: string, safety_order_size: string, price_deviation: string, step_scale: string, volume_scale: string, max_safety_orders: number, take_profit: string, leverage: number, trailing_stop: string, daily_drawdown_limit: string, };
