// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountInfo } from "./AccountInfo";
import type { PerformancePoint } from "./PerformancePoint";

export type OverviewData = { total_capital: number, active_bots: bigint, inactive_bots: bigint, connected_accounts: Array<AccountInfo>, performance_history: Array<PerformancePoint>, };
