// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../backend/bindings/serde_json/JsonValue";

export type SaveStrategyRequest = { name: string, bot_type: string, pair: string, settings: JsonValue, };
