// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveApiKeyRequest = { platform_name: string, label: string, api_key: string, api_secret: string, };
