// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncRequest = { symbol: string, interval: string, start_time: bigint | null, end_time: bigint | null, };
