// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TradeRequest = { provider: string, exchange_id: string, api_key: string, secret: string, symbol: string, side: string, amount: number, price: number | null, };
