// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrailingSettings = { buy_amount: string, trailing_percent: string, rsi_period: number, rsi_buy_level: string, daily_drawdown_limit: string, };
