// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateSettingsRequest = { username: string, notif_signal_enabled: boolean, notif_marketing_enabled: boolean, whatsapp_number: string | null, telegram: string | null, };
