// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfile = { id: number, username: string, email: string, created_at: string, status: string, whatsapp_number: string | null, telegram: string | null, };
