// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserNotification = { id: number, user_id: number | null, title: string, message: string, category: string, created_at: string, is_read: boolean, };
