// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserTrade = { id: number, pair: string, strategy_type: string, side: string, price: string, amount: string, pnl: string | null, created_at: string, status: string, requested_price: string | null, slippage: string | null, market_regime: string | null, is_manual_intervention: boolean | null, intervention_pnl_diff: string | null, error_code: string | null, error_message: string | null, market_session: string | null, notes: string | null, change_history: string | null, };
