export const BINANCE_SYMBOLS = [
  "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "ADAUSDT", "XRPUSDT", "DOTUSDT", "DOGEUSDT", "AVAXUSDT", "LTCUSDT",
  "MATICUSDT", "LINKUSDT", "UNIUSDT", "BCHUSDT", "FILUSDT", "ATOMUSDT", "TRXUSDT", "ETCUSDT", "XLMUSDT", "FTMUSDT"
];
