// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminProfile = { id: number, username: string, email: string, role: string | null, };
