// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminUser = { id: number, username: string, email: string, role: string | null, status: string | null, notif_signal_enabled: boolean | null, notif_marketing_enabled: boolean | null, email_verified: boolean | null, created_at: string, whatsapp_number: string | null, telegram: string | null, };
