// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminOverview = { total_users: bigint, active_bots: bigint, total_trades: bigint, total_profit: number, };
