// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminApiKey = { id: number, username: string, platform_name: string, label: string, created_at: string, status: string | null, };
