// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyStat } from "./DailyStat";
import type { UserTrade } from "../../../frontend/src/types/UserTrade";

export type AdminReport = { recent_trades: Array<UserTrade>, daily_stats: Array<DailyStat>, };
