// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BroadcastRequest = { channels: Array<string>, message: string, user_ids: Array<number> | null, };
