// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketSummary = { symbol: string, interval: string, start_time: bigint, end_time: bigint, count: bigint, };
