// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationSettings = { telegram_bot_token: string, telegram_chat_id_up: string, telegram_chat_id_down: string, whatsapp_group_id_up: string, whatsapp_group_id_down: string, whatsapp_port: string, cooldown_minutes: string, alert_on_errors: string, emergency_template_down: string | null, emergency_template_hacked: string | null, emergency_template_maintenance: string | null, };
