// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpecialNotificationRequest = { user_id: number, message: string, via_telegram: boolean, via_whatsapp: boolean, via_email: boolean | null, };
