// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TelegramBotUpdate = { chat_id: string, username: string | null, first_name: string | null, last_name: string | null, last_message: string | null, date: bigint | null, };
