// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VpsNodeProcess = { id: number, name: string, category: string, status: string, cpu: number, memory: bigint, restarts: number, uptime: bigint, };
